### ISSUE TITLE
Add "named" Versions

### ISSUE THREAD

**Issue by illemonati** [SheepTester/olamreee#19]
# Use the browser localStorage to save specific past versions ("named" versions). 

*so if u mess up big time. you can choose versions to restore to.*

like google docs named versions. (You have to manually click on save to save them, also a input for name)

![image](https://sites.google.com/a/revevol.eu/images-base/version_history6.png)

**Comment by illemonati** [comment]
Also useful for determining between multiple ordering methods.

**Comment by SheepTester** [comment]
You can name versions by adding `?key=SAVECODE_KEY_HERE` to the URL
