### ISSUE TITLE
Issues regarding load

### ISSUE THREAD

**Issue by illemonati** [SheepTester/olamreee#20]
It is not possible for every combination to be "sheep-approved". I refuse to believe that u approved every single combination. 

*Also it makes the save code longer, takes more space.*

# A real issue regarding the load is that any list encoded in base64 does not trigger the problem message.

Please fix this.

**Comment by SheepTester** [comment]
The *real* real issue is where this supposed base64-encoded fake list came from 🤔

The first string is there serving as the savecode version; sheep are superior to numbers
